In [1]:
# Cell 1 — Import library
import pandas as pd

In [2]:
# Cell 2 — Load dataset
df = pd.read_csv("../data/raw/customer_support_tickets.csv")

df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [3]:
# Cell 3 - Inspect dataset shape and structure
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 8469
Columns: 17
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

In [4]:
# Cell 4 — Count missing values in each column
missing_values = df.isnull().sum()

missing_values

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

### Count missing values in each column
Finding:
- 
Interpretation:
- 
Decision:
- ### Missing Values

Finding:
- The following columns contained missing values:
    - Resolution
    - First Response Time
    - Time to resolution
    - Customer Satisfaction Rating

Interpretation:
- The resolution is missing when the issue related to that ticket was not resolved and therefore a Time for the resolution could not be   filled. The first response time contains missing values when no response was attached to that ticket. The missing values on CUstomer Satisfaction rating occur when the customer does not provide feedback on the customer satisfaction page.

Decision:
- Missing Resolution values will be represented as "Not Resolved".
- Missing timestamps will remain missing if they correspond to tickets that have not reached that stage.

Reason:
- A ticket whose issue is not resolved should be tagged as not resolved under the resolution column to facilitate addessing those tickets who still need to be resolved.
- Missing operational timestamps can contain useful business meaning. A ticket that has not been resolved should not be given an artificial resolution time.

In [5]:
# Cell 5 — Count duplicate rows
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [6]:
# Cell 6 - Remove Duplicate Rows
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 8469

### Duplicate Rows

Finding:
- No duplicates were found

Decision:
- Exact duplicate records were removed.

Reason:
- Exact duplicate rows would cause tickets to be counted more than once and could distort later analysis.

In [7]:
# Cell 7 — Inspect column names
df.columns.tolist()

for column in df.columns:
    print(repr(column))

'Ticket ID'
'Customer Name'
'Customer Email'
'Customer Age'
'Customer Gender'
'Product Purchased'
'Date of Purchase'
'Ticket Type'
'Ticket Subject'
'Ticket Description'
'Ticket Status'
'Resolution'
'Ticket Priority'
'Ticket Channel'
'First Response Time'
'Time to Resolution'
'Customer Satisfaction Rating'

In [8]:
# Cell 8 - Verify Whitespaces
df.columns = df.columns.str.strip()

df.columns.tolist()

['Ticket ID',
 'Customer Name',
 'Customer Email',
 'Customer Age',
 'Customer Gender',
 'Product Purchased',
 'Date of Purchase',
 'Ticket Type',
 'Ticket Subject',
 'Ticket Description',
 'Ticket Status',
 'Resolution',
 'Ticket Priority',
 'Ticket Channel',
 'First Response Time',
 'Time to Resolution',
 'Customer Satisfaction Rating']

### Column Names

Finding:
- Column names were inspected for leading and trailing whitespace.

Decision:
- Leading and trailing whitespace was removed from column names.

Reason:
- Consistent column names reduce errors when referencing fields in Python.

In [9]:
# Cell 9 — Inspect data types
df.dtypes

Ticket ID                         int64
Customer Name                    object
Customer Email                   object
Customer Age                      int64
Customer Gender                  object
Product Purchased                object
Date of Purchase                 object
Ticket Type                      object
Ticket Subject                   object
Ticket Description               object
Ticket Status                    object
Resolution                       object
Ticket Priority                  object
Ticket Channel                   object
First Response Time              object
Time to Resolution               object
Customer Satisfaction Rating    float64
dtype: object

In [10]:
# Cell 10 — Convert Date of Purchase to date time
df["Date of Purchase"] = pd.to_datetime(
    df["Date of Purchase"],
    errors="coerce"
)

In [11]:
# Cell 11 — Convert First Response Time to date time
df["First Response Time"] = pd.to_datetime(df["First Response Time"], errors="coerce")

In [12]:
# Cell 12 — Convert Time to Resolution to date time
df["Time to Resolution"] = pd.to_datetime(df["Time to Resolution"], errors="coerce")

# Inspect
df[
    [
        "Date of Purchase",
        "First Response Time",
        "Time to Resolution"
    ]
].dtypes

Date of Purchase       datetime64[ns]
First Response Time    datetime64[ns]
Time to Resolution     datetime64[ns]
dtype: object

### Date and Time Columns

Finding:
- The date/time columns were initially stored in a format that needed explicit conversion.

Decision:
- Date-related columns were converted with pd.to_datetime().
- Invalid values are converted to NaT using errors="coerce".

Reason:
- Datetime values are required for reliable time-based analysis later in the project.

In [13]:
# Cell 13 — Investigate rows with missing resolution.
unresolved_tickets = df.loc[
    df["Resolution"].isnull(),
    [
        "Ticket Status",
        "Resolution",
        "First Response Time",
        "Time to Resolution",
        "Customer Satisfaction Rating"
    ]
]

unresolved_tickets.head(10)

,Ticket Status,Resolution,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,Pending Customer Response,NaN,2023-06-01 12:15:36,NaT,NaN
1,Pending Customer Response,NaN,2023-06-01 16:45:38,NaT,NaN
5,Open,NaN,NaT,NaT,NaN
6,Open,NaN,NaT,NaT,NaN
7,Open,NaN,NaT,NaT,NaN
8,Pending Customer Response,NaN,2023-06-01 10:32:47,NaT,NaN
9,Pending Customer Response,NaN,2023-06-01 09:25:48,NaT,NaN
12,Pending Customer Response,NaN,2023-06-01 19:03:53,NaT,NaN
13,Pending Customer Response,NaN,2023-06-01 20:34:54,NaT,NaN
15,Pending Customer Response,NaN,2023-06-01 15:09:57,NaT,NaN

In [14]:
# Cell 14 - Count tickets with missing resolution
print(
    "Tickets with missing Resolution:",
    df["Resolution"].isnull().sum()
)

Tickets with missing Resolution: 5700

In [15]:
# Cell 15 — Fill the blank cells under Resolution with the value "Not Resolved"
df["Resolution"] = df["Resolution"].fillna("Not Resolved")

# Verify
df["Resolution"].isnull().sum()

np.int64(0)

### Missing Resolution Values

Finding:
- Some tickets did not contain resolution text.

Interpretation:
- These records represent tickets without a recorded resolution.

Decision:
- Missing Resolution values were replaced with "Not Resolved".

Reason:
- This keeps unresolved tickets identifiable instead of treating them as unexplained missing text.

In [16]:
# Cell 16 - Inspect whitespaces in all text columns
text_columns = df.select_dtypes(include="object").columns

text_columns

Index(['Customer Name', 'Customer Email', 'Customer Gender',
       'Product Purchased', 'Ticket Type', 'Ticket Subject',
       'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority',
       'Ticket Channel'],
      dtype='object')

In [17]:
# Cell 17 - Remove leading/trailing whitespace from text columns
for column in text_columns:
    df[column] = df[column].str.strip()

In [18]:
# Cell 18 — Inspect important categorical values
print("Ticket Types:")
print(df["Ticket Type"].value_counts(dropna=False))

print("\nTicket Statuses:")
print(df["Ticket Status"].value_counts(dropna=False))

Ticket Types:
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Ticket Statuses:
Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

In [19]:
# Cell 19 — Normalize categorical capitalization
df["Ticket Type"] = df["Ticket Type"].str.strip().str.title()
df["Ticket Status"] = df["Ticket Status"].str.strip().str.title()

# Verify

print(df["Ticket Type"].value_counts(dropna=False))
print()
print(df["Ticket Status"].value_counts(dropna=False))

Ticket Type
Refund Request          1752
Technical Issue         1747
Cancellation Request    1695
Product Inquiry         1641
Billing Inquiry         1634
Name: count, dtype: int64

Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

### Categorical Consistency

Finding:
- Ticket Type and Ticket Status were inspected for inconsistent spacing and capitalization.

Decision:
- Leading/trailing spaces were removed and category capitalization was standardized.

Reason:
- Values referring to the same category should not be counted separately because of formatting differences.

In [20]:
# Cell 20 — Check satisfaction values
df["Customer Satisfaction Rating"].describe()

df["Customer Satisfaction Rating"].value_counts(
    dropna=False
).sort_index()

invalid_satisfaction = df.loc[
    df["Customer Satisfaction Rating"].notna()
    & ~df["Customer Satisfaction Rating"].between(1, 5)
]

invalid_satisfaction

Empty DataFrame
Columns: [Ticket ID, Customer Name, Customer Email, Customer Age, Customer Gender, Product Purchased, Date of Purchase, Ticket Type, Ticket Subject, Ticket Description, Ticket Status, Resolution, Ticket Priority, Ticket Channel, First Response Time, Time to Resolution, Customer Satisfaction Rating]
Index: []

In [21]:
# Cell 21 — Check remaining missing values
df.isnull().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                         0
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [22]:
# Cell 22 — Verify duplicates again
print("Remaining duplicate rows:", df.duplicated().sum())

Remaining duplicate rows: 0

In [23]:
# Cell 23 — Verify final data types
df.dtypes

Ticket ID                                int64
Customer Name                           object
Customer Email                          object
Customer Age                             int64
Customer Gender                         object
Product Purchased                       object
Date of Purchase                datetime64[ns]
Ticket Type                             object
Ticket Subject                          object
Ticket Description                      object
Ticket Status                           object
Resolution                              object
Ticket Priority                         object
Ticket Channel                          object
First Response Time             datetime64[ns]
Time to Resolution              datetime64[ns]
Customer Satisfaction Rating           float64
dtype: object

In [24]:
# Cell 24 — Final inspection
df.info()
df.head()
df.sample(5, random_state=42)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   datetime64[ns]
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    8469 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   datetime64[ns]
 15  Time to Resolution            2769 non-null   datetime64[ns]
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: datetime64[ns](3), float64(1), int64(2), object(11)
memory usage: 1.1+ MB

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
4830,4831,James Smith,debra98@example.net,69,Female,Roomba Robot Vacuum,2020-03-24,Refund Request,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Not Resolved,High,Phone,2023-06-01 12:59:31,NaT,NaN
7075,7076,Erica Reed,carsonjames@example.net,64,Male,Roomba Robot Vacuum,2021-01-22,Product Inquiry,Battery life,I'm having trouble connecting my {product_purc...,Closed,Write economy could station face wall thus.,Low,Social media,2023-06-01 02:08:59,2023-06-01 10:49:59,4.0
4715,4716,Mrs. Madison Thompson MD,taylorjames@example.com,41,Female,Philips Hue Lights,2020-06-07,Billing Inquiry,Refund request,I'm having an issue with the {product_purchase...,Open,Not Resolved,Low,Chat,NaT,NaT,NaN
2022,2023,Sarah Nunez,martinezkenneth@example.org,62,Other,LG OLED,2021-02-20,Billing Inquiry,Peripheral compatibility,I'm having an issue with the {product_purchase...,Closed,Three his cut save upon animal have.,High,Social media,2023-06-01 13:54:11,2023-06-01 08:10:11,4.0
676,677,James White,rivasdavid@example.org,51,Female,Roomba Robot Vacuum,2021-08-01,Refund Request,Peripheral compatibility,I'm having an issue with the {product_purchase...,Open,Not Resolved,Medium,Social media,NaT,NaT,NaN

In [25]:
# Cell 25 — Produce a cleaning summary
print("FINAL CLEANING SUMMARY")
print("----------------------")
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Duplicate rows:", df.duplicated().sum())
print()
print("Remaining missing values:")
print(df.isnull().sum())

FINAL CLEANING SUMMARY
----------------------
Rows: 8469
Columns: 17
Duplicate rows: 0

Remaining missing values:
Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                         0
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [26]:
# Cell 26 — Export the cleaned dataset
from pathlib import Path

Path("../data/processed").mkdir(
    parents=True,
    exist_ok=True
)
df.to_csv(
    "../data/processed/customer_support_tickets_clean.csv",
    index=False
)

In [27]:
# Cell 27 — Verify that the exported file can be reopened
clean_df = pd.read_csv(
    "../data/processed/customer_support_tickets_clean.csv"
)

clean_df.head()

print(clean_df.shape)

(8469, 17)